dist: trusty
language: rust
services: docker
sudo: required
env:
  global:
    # This will be part of the release tarball
    # TODO change the project name
    - CRATE_NAME=rdp
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    # GH_TOKEN
    - secure: duS4EzFgamSd0mhi/MVsWnnyZpn9031VFSmoNIaLocP/vLRalkewMf/vkc2QCt6L4uJgts6kL3j3JcC9lYa5D6MJwwyAxkn6KwivrG6g/Z+mywjDll+P9iqIF96O0okFxnITu3I4yZDsYb9ERH25sfYzetAFbvjc3vOL8FD6bHboo65iukDWrl18QS8qdHycAb7Q9mxjK+0HbP0IjlROLhjzwJ3/xQ40Cv2xgZKnNGH2QsrbLhnKvrvoScU7AZR3gw5XaNWyiVkVmHEfwNwFYX/LDAeTIzH3sdYFTjersDHLFbmTzLSQuIHfEvSzzBdvasUiZIGF/rsFjjhsov5pjXRbwaZUHrPH6Gkmx916T/vZyWeg38QJvsdZ6n//gbas+Nnr4g/mvVGfZDlr1+RTKZWCmf5HjuC3Wsa59RTkr1+d7p2tefUk52N4cPcn+MF/zXT8EmnL//O/QNjQaLMdmYvnQcWykMtwY2JkHgiuNRy7LRO9NACDw16rVjM0HNGI3XXGTYwL0cB02SSSAkK4/8dHspc8XT57/QLW1XTqk1osgbrTNXxx9ajwpKkXKdbfXmN2hxGHtixtQrwgWEZTuWC6E70RTfLYnu62bZ/jaqx2E/EDVZu3/wq1vBLcal1UCYh9L3ln3RtEAzKNPUtHBKGeEfkaZ+i52jLoUir4lCo=


# AFAICT There are a few ways to set up the build jobs. This one is not the DRYest but I feel is the
# easiest to reason about.
# TODO Feel free to remove the channels/targets you don't need
# NOTE Make *sure* you don't remove a reference (&foo) if you are going to dereference it (*foo)
matrix:
  include:
    # Stable channel
    # - os: osx
    #   rust: stable
    #   env: TARGET=i686-apple-darwin
    # - os: linux
    #   rust: stable
    #   env: TARGET=i686-unknown-linux-gnu
    #   addons:
    #     apt:
    #       packages: &i686_unknown_linux_gnu
    #         # Cross compiler and cross compiled C libraries
    #         - gcc-multilib

    ###############################
    - os: osx
      osx_image: xcode7.3
      rust: stable
      env: TARGET=x86_64-apple-darwin
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
      services: docker
    # Beta channel
    # - os: osx
    #   rust: beta
    #   env: TARGET=i686-apple-darwin
    # - os: linux
    #   rust: beta
    #   env: TARGET=i686-unknown-linux-gnu
    #   addons:
    #     apt:
    #       packages: *i686_unknown_linux_gnu
    ############################
    - os: osx
      rust: beta
      osx_image: xcode7.3
      env: TARGET=x86_64-apple-darwin
    - os: linux
      rust: beta
      env: TARGET=x86_64-unknown-linux-gnu


    # Nightly channel
    # - os: osx
    #   rust: nightly
    #   env: TARGET=i686-apple-darwin
    # - os: linux
    #   rust: nightly
    #   env: TARGET=i686-unknown-linux-gnu
    #   addons:
    #     apt:
    #       packages: *i686_unknown_linux_gnu

    ############
    - os: osx
      osx_image: xcode7.3
      rust: nightly
      env: TARGET=x86_64-apple-darwin
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu

  allow_failures:
    # Target `i686-unknown-linux-gnu` is currently only available on the nightly channel
    - os: linux
      rust: stable
      env: TARGET=i686-unknown-linux-gnu
    - os: linux
      rust: beta
      env: TARGET=i686-unknown-linux-gnu

before_install:
  - set -e

before_script: |
  PKGNAME="${TRAVIS_REPO_SLUG}" # must match with cargo.toml
  LOCAL="~/.local" # install here to avoid `sudo`
  pip install travis-cargo --user &&
  export PATH=$HOME/.local/bin:$PATH

install:
  - bash ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

after_success:
  - if [[ "$TARGET" == "x86_64-unknown-linux-gnu" ]]; then docker pull $DOCKER_IMAGE; fi

before_deploy:
  - if ! [[ "$TARGET" == "x86_64-unknown-linux-gnu" ]]; then bash ci/before_deploy.sh; fi
  - if [[ "$TARGET" == "x86_64-unknown-linux-gnu" ]]; then sudo docker run -e TRAVIS_TAG="$TRAVIS_TAG" --rm -v `pwd`:/io $DOCKER_IMAGE /io/ci/manylinux_rust.sh; fi
  # - sudo chown $USER ${CRATE_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz
  
deploy:
  # TODO Regenerate this api_key for your project, this one won't work for you. Here's how:
  # - Go to 'https://github.com/settings/tokens/new' and generate a Token with only the
  # `public_repo` scope enabled
  # - Call `travis encrypt $github_token` where $github_token is the token you got in the previous
  # step and `travis` is the official Travis CI gem (see https://rubygems.org/gems/travis/)
  # - Enter the "encrypted value" below
  api_key:
        - secure: qpSSpMyDAlyoPEiNcimsA+zhAQCx9s242DkxUnVvKWWNeWuIdg9Cr5vMIAG0wDv0xoem7rLXpWI3g3Y1lrNI7rtFfsqB6ayRNYG1MSYeudYOa0nl0NShAGEifGsamBuJ3hvlAszR3+VcX4X0gV1kn50RHtAB4mnPFn9Hj3sAPzvB+/lOZHAbuVHJYI2Rmq5SLqIIzUi44qpO/Yrb3D9nT56kWJN3ZSngG7eZIdkk5ThTRqu/zzATQKCpQn9ci1DlSYLBcNJ3py2fQ2FZaT63k/BWU4CoC7U59kzyVcQYjERadGkZ2Z1zl1dRlAkAyW+Qgh/fo7XRfIQqkAyVk79xrsZSeY/4iEHqaAQNjFboQBcb+vCP0wv6g0huaa7jrEiuTUsDXeSb/nHPyk7ibCz1iU+GXRAO8dSQvzC8tLH7GwQkKcEMzf6p37hoae3I1/w+ZgP6a8zAL8tuyxdEaYlIc3G4v6WIJT7Z6zz88VLXAMFQ2MSoLAYeM7eNcoGsxMe4XciNLxPIlQxLm2n6Fsnc1yuYk4DAwgw2t2PgBl0X1FZnYzgEJk0NKIBfwFEERDDOlj5fCmkrJ4bNVAJvNO7xxhMOqF1E3iL2uxwrnhdl4s0ALaH5yFOBHHBrEnHgznJrbxgGQKG8LL7dHwekXA6P9sgWW2efxni0nPZ+b+DnS/k=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  # don't delete the artifacts from previous phases
  skip_cleanup: true
  # deploy when a new tag is pushed
  on:
    # TODO Here you can pick which targets will generate binary releases
    # In this example, there are some targets that are tested using the stable
    # and nightly channels. This condition makes sure there is only one release
    # for such targets and that's generated using the stable channel
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
