[package]
name = "rdp"
version = "0.1.0"
authors = ["Stephan Hügel <urschrei@gmail.com>"]
description = "A Rust implementation of the Ramer–Douglas–Peucker algorithm"
readme = "README.md"
keywords = ["geo"]
repository = "https://github.com/urschrei/rdp"
license = "MIT"

[dependencies]
