[package]
name = "rdp"
version = "0.1.5"
authors = ["Stephan Hügel <urschrei@gmail.com>"]
description = "A Rust implementation of the Ramer–Douglas–Peucker algorithm"
readme = "README.md"
keywords = ["geo"]
repository = "https://github.com/urschrei/rdp"
license = "MIT"

[dependencies]
libc = "0.2.14"
geo = "0.2.5"
num = "0.1"

[lib]
name = "rdp"
crate-type = ["rlib", "dylib"]
test = true
doctest = false
doc = true

[profile.release]
rpath = true
