[package]
name = "rdp"
version = "0.2.44"
authors = ["Stephan Hügel <urschrei@gmail.com>"]
description = "A Rust implementation of the Ramer–Douglas–Peucker and Visvalingam-Whyatt algorithms"
readme = "README.md"
keywords = ["geo", "Ramer", "Douglas-Peucker", "Visvalingam-Whyatt"]
repository = "https://github.com/urschrei/rdp"
license = "MIT"
# we only need to run this if the public API changes
# build = "src/build.rs"

[dependencies]
libc = "0.2.14"
geo = "0.4.10"
num = "0.1"

[build-dependencies]
moz-cheddar = "0.4.0"

[lib]
name = "rdp"
crate-type = ["cdylib"]
test = true
doctest = false
doc = true

[profile.release]
rpath = true
lto = true
